/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import Controle.ReceitasControle;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Receitas;
import persistencia.ReceitasPersistencia;
import static persistencia.ReceitasPersistencia.listarComboBoxDescricaoReceita;

/**
 *
 * @author Sciencegamer
 */
public class TelaDescricaoReceita extends javax.swing.JFrame {

    ReceitasPersistencia rPersist = new ReceitasPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Receitas.txt");
    ReceitasControle rControle = new ReceitasControle();

    /**
     * Creates new form TelaDescricaoReceita
     */
    public TelaDescricaoReceita() throws Exception {
        initComponents();
        listarComboBoxDescricaoReceita(comboBoxR);
        tableReceita.setAutoCreateRowSorter(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReceita = new javax.swing.JTable();
        botaoListar = new javax.swing.JButton();
        comboBoxR = new javax.swing.JComboBox<>();
        botaoVoltar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "DESCRIÇÃO", "VALOR", "DATA", "CONTA", "CARTÃO"
            }
        ));
        jScrollPane1.setViewportView(tableReceita);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 740, 195));

        botaoListar.setBackground(new java.awt.Color(0, 0, 0));
        botaoListar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoListar.setForeground(new java.awt.Color(255, 255, 255));
        botaoListar.setText("Descrecer receita");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 29));

        comboBoxR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 161, 30));

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 185, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel9.setText("MyCash Visualizar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("Receitas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        TelaFundo.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        TelaFundo.setForeground(new java.awt.Color(255, 255, 255));
        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaVisualizarReceitas.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        try {
            ArrayList<Receitas> aux = rControle.listagem();
            DefaultTableModel model = (DefaultTableModel) tableReceita.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < aux.size(); pos++) {
                String[] saida = new String[6];
                    Receitas r1 = aux.get(pos);
                    String aux1= comboBoxR.getSelectedItem()+"";
                if (r1.getDescricao().equals(aux1)) {
                    
                    saida[0] = r1.getId() + "";
                    saida[1] = r1.getDescricao() + "";
                    DecimalFormat df = new DecimalFormat("R$#,##0.00");
                    saida[2] = df.format(r1.getValor());
                    saida[3] = r1.getData();
                    saida[4] = r1.getConta();
                    saida[5] = r1.getCartao();

                    //incluir nova linha na tabela
                    model.addRow(saida);
                }
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        try {
            TelaMenuDeVisualizacao nova;
            nova = new TelaMenuDeVisualizacao();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaDescricaoReceita().setVisible(true);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(TelaDescricaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoListar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxR;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReceita;
    // End of variables declaration//GEN-END:variables
}
