/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import java.lang.System.Logger;
import java.text.DecimalFormat;
import java.util.logging.Level;
import static persistencia.DespesasPersistencia.listarComboBoxDescricaoDespesa;
import static persistencia.DespesasPersistencia.listarComboBoxDespesa3;
import persistencia.ListagensDeVisualizacao;

/**
 *
 * @author Sciencegamer
 */
public class TelaMenuDeVisualizacao extends javax.swing.JFrame {

    ListagensDeVisualizacao LDV = new ListagensDeVisualizacao();

    /**
     * Creates new form TelaMenuDeVisualizacao
     */
    public TelaMenuDeVisualizacao() throws Exception {
        initComponents();
        listarComboBoxDespesa3(comboBoxCartao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoMensal = new javax.swing.JButton();
        botaoLancamentos = new javax.swing.JButton();
        botaoDespesasDescricao = new javax.swing.JButton();
        botaoReceitasDescricao = new javax.swing.JButton();
        botaoFatura = new javax.swing.JButton();
        comboBoxCartao = new javax.swing.JComboBox<>();
        textFatura = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoMensal.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoMensal.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoMensal.setForeground(new java.awt.Color(255, 255, 255));
        botaoMensal.setText("Lançamentos do mês");
        jPanel1.add(botaoMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 313, -1));

        botaoLancamentos.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoLancamentos.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoLancamentos.setForeground(new java.awt.Color(255, 255, 255));
        botaoLancamentos.setText("Visualizar todos os Lançamentos");
        botaoLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLancamentosActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLancamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        botaoDespesasDescricao.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoDespesasDescricao.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoDespesasDescricao.setForeground(new java.awt.Color(255, 255, 255));
        botaoDespesasDescricao.setText("Visualizar despesas a partir de uma descrição");
        botaoDespesasDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDespesasDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoDespesasDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        botaoReceitasDescricao.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoReceitasDescricao.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoReceitasDescricao.setForeground(new java.awt.Color(255, 255, 255));
        botaoReceitasDescricao.setText("Visualizar receitas a partir de uma descrição");
        botaoReceitasDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReceitasDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoReceitasDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, -1));

        botaoFatura.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoFatura.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoFatura.setForeground(new java.awt.Color(255, 255, 255));
        botaoFatura.setText("Fatura atual do cartão");
        botaoFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFaturaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 310, -1));

        comboBoxCartao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        textFatura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textFatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFaturaKeyTyped(evt);
            }
        });
        jPanel1.add(textFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 187, -1));

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoVoltar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar ao menu principal");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("MyCash Financeiro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        TelaFundo.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        TelaFundo.setForeground(new java.awt.Color(255, 255, 255));
        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaMenuVisualização.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLancamentosActionPerformed
        TelaVisualizarTodos nova = new TelaVisualizarTodos();
        this.dispose();
        nova.setVisible(true);
    }//GEN-LAST:event_botaoLancamentosActionPerformed

    private void botaoFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFaturaActionPerformed
        try {
            String cartaoAux = comboBoxCartao.getSelectedItem() + "";
            int cartao = Integer.parseInt(cartaoAux);
            double aux = LDV.retornaFatura(cartao);
            DecimalFormat df = new DecimalFormat("R$#,##0.00");
            String aux1 = df.format(aux);
            textFatura.setText(aux1 + "");
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoFaturaActionPerformed

    private void textFaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFaturaKeyTyped
        evt.consume();
    }//GEN-LAST:event_textFaturaKeyTyped

    private void botaoDespesasDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDespesasDescricaoActionPerformed

        try {
            TelaDescricaoDespesa nova;
            nova = new TelaDescricaoDespesa();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoDespesasDescricaoActionPerformed

    private void botaoReceitasDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReceitasDescricaoActionPerformed
        try {
            TelaDescricaoReceita nova;
            nova = new TelaDescricaoReceita();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoReceitasDescricaoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        try {
            TelaMenu nova;
            nova = new TelaMenu();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaMenuDeVisualizacao().setVisible(true);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(TelaMenuDeVisualizacao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoDespesasDescricao;
    private javax.swing.JButton botaoFatura;
    private javax.swing.JButton botaoLancamentos;
    private javax.swing.JButton botaoMensal;
    private javax.swing.JButton botaoReceitasDescricao;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxCartao;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFatura;
    // End of variables declaration//GEN-END:variables
}
