/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import Controle.CartaoControle;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Cartao;

import persistencia.CartaoPersistencia;
import static persistencia.DespesasPersistencia.listarComboBoxDespesa2;

/**
 *
 * @author Sciencegamer
 */
public class TelaCartao extends javax.swing.JFrame {

    CartaoControle cControle = new CartaoControle();
    CartaoPersistencia cPersistencia = new CartaoPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Cartoes.txt");

    /**
     * Creates new form TelaCartao
     */
    public TelaCartao() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        mostrarListagem();
        tableCartoes.setAutoCreateRowSorter(true);
        listarComboBoxDespesa2(comboBoxConta);
    }

    public void limparTela() {
        textId.setText("");
        textNumero.setText("");
        textNome.setText("");
        textFechamento.setText("");
        textPagamento.setText("");
        textCvv.setText("");
        textBandeira.setText("");
        textLimite.setText("");
        textAgencia.setText("");
        textTaxa.setText("00.00%");
        textValidade.setToolTipText("");
        comboBoxConta.setSelectedIndex(0);

    }

    private void mostrarListagem() {
        try {
            ArrayList<Cartao> aux = cControle.listagem();
            DefaultTableModel model = (DefaultTableModel) tableCartoes.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < aux.size(); pos++) {
                String[] saida = new String[12];
                Cartao c1 = aux.get(pos);
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                DecimalFormat df1 = new DecimalFormat("#,###0.00");

                saida[0] = c1.getId() + "";
                String number = c1.getNumero();                
                number = number.substring(0, 4) + "-" + number.substring(4, 8) + "-" + number.substring(8, 12) + "-" + number.substring(12, 16);
                saida[1] = number;
                saida[2] = c1.getNome() + "";
                saida[3] = c1.getValidade() + "";
                saida[4] = c1.getDiaDoFechamento() + "";
                saida[5] = c1.getDiaDoPagamento() + "";
                saida[6] = c1.getCvv() + "";
                saida[7] = c1.getBandeira() + "";
                String sup= c1.getLimite()+"";
                if(sup.equals("0.0")){
                    saida[8]="Cartão de débito";
                }
                else{
                    saida[8] = df.format(c1.getLimite());
                }                
                saida[9] = c1.getAgencia() + "";
                saida[10] = c1.getConta() + "";
                saida[11] = df1.format(c1.getTaxa()) + "%";

                //incluir nova linha na tabela
                model.addRow(saida);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textCvv = new javax.swing.JTextField();
        textBandeira = new javax.swing.JTextField();
        textLimite = new javax.swing.JTextField();
        textAgencia = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textFechamento = new javax.swing.JTextField();
        textPagamento = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCartoes = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        textValidade = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        textTaxa = new javax.swing.JTextField();
        comboBoxConta = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cartões");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(805, 805, 805))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Identificador:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Número:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Validade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Fechamento da fatura:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Pagamento da fatura:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("CVV:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Bandeira:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Limite de crédito**:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Identificador da Conta*:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Agência:");

        textCvv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textCvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCvvKeyTyped(evt);
            }
        });

        textBandeira.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textBandeira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBandeiraKeyTyped(evt);
            }
        });

        textLimite.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textLimite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textLimiteKeyTyped(evt);
            }
        });

        textAgencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAgenciaKeyTyped(evt);
            }
        });

        textId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIdKeyTyped(evt);
            }
        });

        textNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });

        textNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        textFechamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textFechamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechamentoKeyTyped(evt);
            }
        });

        textPagamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPagamentoKeyTyped(evt);
            }
        });

        jButtonIncluir.setBackground(new java.awt.Color(0, 255, 255));
        jButtonIncluir.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonConsultar.setBackground(new java.awt.Color(0, 255, 255));
        jButtonConsultar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonConsultar.setText("Consultar por ID");
        jButtonConsultar.setPreferredSize(new java.awt.Dimension(190, 33));
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(0, 255, 255));
        jButtonAlterar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonAlterar.setText("Alterar por ID");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(0, 255, 255));
        jButtonExcluir.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonExcluir.setText("Apagar por ID");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        tableCartoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableCartoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "NUMERO", "NOME", "VALIDADE", "FECHAMENTO DA FATURA", "PAGAMENTO DA FATURA", "CVV", "BANDEIRA", "LIMITE DE CRÉDITO", "AGENCIA", "CONTA", "TAXA DE JUROS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCartoes);
        if (tableCartoes.getColumnModel().getColumnCount() > 0) {
            tableCartoes.getColumnModel().getColumn(1).setMinWidth(200);
        }

        botaoVoltar.setBackground(new java.awt.Color(0, 255, 255));
        botaoVoltar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoVoltar.setText("Voltar ao menu principal");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("*Identificador 0 significa que o cartão não possui vínculo com uma conta");

        textValidade.setDateFormatString("MM/yy");
        textValidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Taxa de juros:");

        textTaxa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textTaxa.setText("00.00%");
        textTaxa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTaxaKeyTyped(evt);
            }
        });

        comboBoxConta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("**Se o cartão não possui a função crédito digite 0 no campo de limite de crédito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textValidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFechamento, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                            .addComponent(textTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                            .addComponent(textLimite, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                            .addComponent(textPagamento)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(152, 152, 152)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(botaoVoltar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCvv, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                    .addComponent(comboBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textBandeira, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                        .addComponent(textAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1764, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(textBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(textCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(textAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(comboBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(textValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/yy");
            String validade = dateFormat.format(textValidade.getDate());
            if (textId.getText().equals("") || textNome.getText().equals("") || textNumero.getText().equals("")||textLimite.getText().equals("")
                    || validade.equals("") || textFechamento.getText().equals("") || textPagamento.getText().equals("")
                    || textAgencia.getText().equals("") || textCvv.getText().equals("") || textBandeira.getText().equals("")) {
                throw new Exception("Algum dos campos está vazio");
            }

            int id = Integer.parseInt(textId.getText());
            if(textNumero.getText().length()<16){
                throw new Exception("O número de um cartão tem 16 dígitos");
            }
            String numero = textNumero.getText();           
            
            String nome = textNome.getText();                  
            int diaDoFechamento = Integer.parseInt(textFechamento.getText());
            int diaDoPagamento = Integer.parseInt(textPagamento.getText());
            int cvv = Integer.parseInt(textCvv.getText());
            String bandeira = textBandeira.getText();
            String aux1 = textLimite.getText().replaceAll(",", ".");
            double limite = Double.parseDouble(aux1);
            int agencia = Integer.parseInt(textAgencia.getText());
            String conta = comboBoxConta.getSelectedItem() + "";

            aux1 = textTaxa.getText().replaceAll("%", "");
            aux1 = aux1.replaceAll(",", ".");
            double taxa = Double.parseDouble(aux1);

            Cartao aux = new Cartao(id, numero, nome, validade, diaDoFechamento, diaDoPagamento, cvv, bandeira,
                    limite, agencia, conta, taxa);
            cControle.incluir(aux);

            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        try {
            String str = textId.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }
            int id = Integer.parseInt(str);
            Cartao aux = cControle.consultarPorId(id);
            if (aux == null) {
                throw new Exception("Cartão não existe");
            }

            textId.setText(aux.getId() + "");
            for (int i = 0; i < comboBoxConta.getItemCount(); i++) {
                String x1 = comboBoxConta.getItemAt(i);
                if (x1.equals(aux.getConta())) {
                    comboBoxConta.setSelectedItem(x1);
                }
            }
            
            textNumero.setText(aux.getNumero() + "");
            textNome.setText(aux.getNome());
            Date date1 = new SimpleDateFormat("MM/yy").parse(aux.getValidade());
            textValidade.setDate(date1);
            textFechamento.setText(aux.getDiaDoFechamento() + "");
            textPagamento.setText(aux.getDiaDoPagamento() + "");
            textCvv.setText(aux.getCvv() + "");
            textBandeira.setText(aux.getBandeira());
            DecimalFormat df2 = new DecimalFormat("#,##0.00");
            textLimite.setText(df2.format(aux.getLimite()));
            textAgencia.setText(aux.getAgencia() + "");
            textTaxa.setText(df2.format(aux.getTaxa()) + "%");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {
            String str1 = textId.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/yy");
            String validade = dateFormat.format(textValidade.getDate());
            if (textId.getText().equals("") || textNome.getText().equals("") || textNumero.getText().equals("")||textLimite.getText().equals("")
                    || validade.equals("") || textFechamento.getText().equals("") || textPagamento.getText().equals("")
                    || textAgencia.getText().equals("") || textCvv.getText().equals("") || textBandeira.getText().equals("")) {
                throw new Exception("Algum dos campos está vazio");
            }

            if (str1.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }

            Cartao aux = new Cartao();

            aux.setId(Integer.parseInt(str1));
            if(textNumero.getText().length()<16){
                throw new Exception("O número de um cartão tem 16 dígitos");
            }
            aux.setNumero(textNumero.getText());
            aux.setNome(textNome.getText());            
            aux.setValidade(dateFormat.format(textValidade.getDate()));
            aux.setDiaDoFechamento(Integer.parseInt(textFechamento.getText()));
            aux.setDiaDoPagamento(Integer.parseInt(textPagamento.getText()));
            aux.setCvv(Integer.parseInt(textCvv.getText()));
            aux.setBandeira(textBandeira.getText());
            String aux1 = textLimite.getText().replaceAll(",", ".");
            aux.setLimite(Double.parseDouble(aux1));
            aux.setAgencia(Integer.parseInt(textAgencia.getText()));
            aux.setConta(comboBoxConta.getSelectedItem() + "");

            aux1 = textTaxa.getText().replaceAll("%", "");
            aux1 = aux1.replaceAll(",", ".");
            aux.setTaxa(Double.parseDouble(aux1));

            cControle.alterar(Integer.parseInt(str1), aux);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            String str = textId.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }
            int id = Integer.parseInt(str);
            cControle.apagarPorId(id);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        TelaMenu nova2 = new TelaMenu();
        this.dispose();
        nova2.setVisible(true);

    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void textIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_textIdKeyTyped

    private void textFechamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechamentoKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
        if (textFechamento.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_textFechamentoKeyTyped

    private void textPagamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPagamentoKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
        if (textPagamento.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_textPagamentoKeyTyped

    private void textCvvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCvvKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
        if (textCvv.getText().length() > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_textCvvKeyTyped

    private void textTaxaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTaxaKeyTyped
        char test = evt.getKeyChar();
        if (test != ',') {
            if (test != '.') {
                if (test != '%') {
                    if (!Character.isDigit(test)) {
                        evt.consume();
                    }
                }

            }
        }
    }//GEN-LAST:event_textTaxaKeyTyped

    private void textAgenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAgenciaKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_textAgenciaKeyTyped

    private void textLimiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLimiteKeyTyped
        char test = evt.getKeyChar();
        if (test != ',') {
            if (test != '.') {
                if (!Character.isDigit(test)) {
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_textLimiteKeyTyped

    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
        if (textNumero.getText().length() > 15) {
            evt.consume();
        }
    }//GEN-LAST:event_textNumeroKeyTyped

    private void textBandeiraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBandeiraKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isLetter(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_textBandeiraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCartao().setVisible(true);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(TelaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxConta;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCartoes;
    private javax.swing.JTextField textAgencia;
    private javax.swing.JTextField textBandeira;
    private javax.swing.JTextField textCvv;
    private javax.swing.JTextField textFechamento;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textLimite;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPagamento;
    private javax.swing.JTextField textTaxa;
    private com.toedter.calendar.JDateChooser textValidade;
    // End of variables declaration//GEN-END:variables
}
