/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import Controle.ReceitasControle;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Receitas;
import static persistencia.DespesasPersistencia.listarComboBoxDespesa;
import static persistencia.DespesasPersistencia.listarComboBoxDespesa2;
import persistencia.ReceitasPersistencia;

/**
 *
 * @author Sciencegamer
 */
public class TelaReceita extends javax.swing.JFrame {

    ReceitasControle rControle = new ReceitasControle();
    ReceitasPersistencia rPersistencia = new ReceitasPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Receitas.txt");

    /**
     * Creates new form TelaReceita
     */
    public TelaReceita() throws Exception {
        initComponents();        
        mostrarListagem();
        tableReceita.setAutoCreateRowSorter(true);
        listarComboBoxDespesa(comboBoxCartao);
        listarComboBoxDespesa2(comboBoxConta);
    }

    public void limparTela() {
        textId.setText("");
        textDescricao.setText("");
        textValor.setText("");        
        comboBoxCartao.setSelectedIndex(0);
        textDate.setDate(null);
        comboBoxConta.setSelectedIndex(0);

    }

    private void mostrarListagem() {
        try {
            ArrayList<Receitas> aux = rControle.listagem();
            DefaultTableModel model = (DefaultTableModel) tableReceita.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < aux.size(); pos++) {
                String[] saida = new String[6];
                Receitas r1 = aux.get(pos);
                saida[0] = r1.getId() + "";
                saida[1] = r1.getDescricao() + "";
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                saida[2] = df.format(r1.getValor());
                saida[3] = r1.getData();
                saida[4] = r1.getConta();
                saida[5] = r1.getCartao();

                //incluir nova linha na tabela
                model.addRow(saida);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReceita = new javax.swing.JTable();
        botaoConsultar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoIncluir = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        textDate = new com.toedter.calendar.JDateChooser();
        comboBoxCartao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboBoxConta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setText("IDENTIFICADOR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel3.setText("DESCRIÇÃO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        textId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIdKeyTyped(evt);
            }
        });
        jPanel1.add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 150, 30));

        textDescricao.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel1.add(textDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 150, 30));

        tableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "DESCRIÇÃO", "VALOR", "DATA", "CONTA", "CARTÃO"
            }
        ));
        jScrollPane1.setViewportView(tableReceita);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 830, 170));

        botaoConsultar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoConsultar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoConsultar.setForeground(new java.awt.Color(255, 255, 255));
        botaoConsultar.setText("Consulta por ID");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 200, 30));

        botaoExcluir.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoExcluir.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluir.setText("Excluir por ID");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(botaoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 200, 30));

        botaoIncluir.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoIncluir.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoIncluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(botaoIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 200, 30));

        botaoAlterar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoAlterar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAlterar.setText("Alterar ");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 200, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel4.setText("VALOR:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 105, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel5.setText("DATA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 105, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel6.setText("CARTÃO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 105, -1));

        textValor.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorActionPerformed(evt);
            }
        });
        textValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textValorKeyTyped(evt);
            }
        });
        jPanel1.add(textValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, 30));

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoVoltar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Menu principal");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 200, 30));

        textDate.setDateFormatString("dd/MM/yy");
        textDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 30));

        comboBoxCartao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 140, 31));

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel7.setText("CONTA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 105, -1));

        comboBoxConta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 140, 31));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("MyCash Receitas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        TelaFundo.setFont(new java.awt.Font("Lucida Grande", 3, 48)); // NOI18N
        TelaFundo.setForeground(new java.awt.Color(255, 255, 255));
        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaReceita.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 930, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
            String data = dateFormat.format(textDate.getDate());
            if (textId.getText().equals("") || textDescricao.getText().equals("") || textValor.getText().equals("")
                    || data.equals("")) {
                throw new Exception("Algum dos campos está vazio");
            }
            int id = Integer.parseInt(textId.getText());
            String descricao = textDescricao.getText();
            String aux1 = textValor.getText().replaceAll(",", ".");
            Double valor = Double.parseDouble(aux1);            
            String conta = comboBoxConta.getSelectedItem()+"";            
            String cartao = comboBoxCartao.getSelectedItem()+"";            

            Receitas aux = new Receitas(id, descricao, valor, data, conta, cartao);
            rControle.criar(aux);

            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        try {
            String str = textId.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }
            int id = Integer.parseInt(str);
            Receitas aux = rControle.consultar(id);
            if (aux == null) {
                throw new Exception("Receita não existe");
            }
            DecimalFormat df1 = new DecimalFormat("#,##0.00");
            String aux1;
            for (int i = 0; i < comboBoxCartao.getItemCount(); i++) {
                aux1 = comboBoxCartao.getItemAt(i);
                if (aux1.equals(aux.getCartao())) {
                    comboBoxCartao.setSelectedItem(aux1);
                }
            }  
            
            for (int i = 0; i < comboBoxConta.getItemCount(); i++) {
                aux1 = comboBoxConta.getItemAt(i);
                if (aux1.equals(aux.getConta())) {
                    comboBoxConta.setSelectedItem(aux1);
                }
            }
            
            textId.setText(aux.getId() + "");
            textDescricao.setText(aux.getDescricao() + "");
            textValor.setText(df1.format(aux.getValor()));
            Date date1 = new SimpleDateFormat("dd/MM/yy").parse(aux.getData());
            textDate.setDate(date1);            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        try {
            String str = textId.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }
            int id = Integer.parseInt(str);
            rControle.deletar(id);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        try {
            String str1 = textId.getText();
            if (str1.length() == 0) {
                throw new Exception("Identificador da tela está vazio");
            }
            Receitas aux = new Receitas();
            aux.setId(Integer.parseInt(str1));
            aux.setDescricao(textDescricao.getText());
            aux.setValor(Double.parseDouble(textValor.getText()));
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
            aux.setData (dateFormat.format(textDate.getDate()));            
            aux.setCartao(comboBoxCartao.getSelectedItem()+"");
            aux.setConta(comboBoxConta.getSelectedItem()+"");

            rControle.alterar(aux);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        TelaMenu nova2 = new TelaMenu();
        this.dispose();
        nova2.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void textIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_textIdKeyTyped

    private void textValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorKeyTyped
        char test = evt.getKeyChar();
        if (test!=',') {
            if (test!='.') {
                if (!Character.isDigit(test)) {
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_textValorKeyTyped

    private void textValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaReceita().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaReceita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxCartao;
    private javax.swing.JComboBox<String> comboBoxConta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReceita;
    private com.toedter.calendar.JDateChooser textDate;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
