/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import Controle.DespesasControle;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Despesas;
import persistencia.DespesasPersistencia;
import static persistencia.DespesasPersistencia.listarComboBoxDescricaoDespesa;


/**
 *
 * @author Sciencegamer
 */
public class TelaDescricaoDespesa extends javax.swing.JFrame {
    DespesasPersistencia dPersist = new DespesasPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Despesas.txt");
    DespesasControle dControle = new DespesasControle();
    

    /**
     * Creates new form TelaVisualizarDescricao
     */
    public TelaDescricaoDespesa() throws Exception {
        initComponents();
        tableDespesa.setAutoCreateRowSorter(true);
        listarComboBoxDescricaoDespesa(comboBoxD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoListar = new javax.swing.JButton();
        comboBoxD = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDespesa = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoListar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoListar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoListar.setForeground(new java.awt.Color(255, 255, 255));
        botaoListar.setText("Descrever despesas");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 240, -1));

        comboBoxD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 210, 30));

        tableDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "DESCRIÇÃO", "VALOR", "DATA", "CARTÃO", "TIPO", "PARCELAS", "CONTA"
            }
        ));
        jScrollPane1.setViewportView(tableDespesa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 880, 200));

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoVoltar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("Despesas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel9.setText("MyCash Visualizar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        TelaFundo.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        TelaFundo.setForeground(new java.awt.Color(255, 255, 255));
        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaVisualizarDespesas.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        try {
            ArrayList<Despesas> aux = dControle.listagem();
            DefaultTableModel model = (DefaultTableModel) tableDespesa.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < aux.size(); pos++) {
                String[] saida = new String[8];
                Despesas d1 = aux.get(pos);
                String aux1= comboBoxD.getSelectedItem()+"";
                if(d1.getDescricao().equals(aux1)){
                    saida[0] = d1.getId() + "";
                saida[1] = d1.getDescricao();
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                saida[2] = df.format(d1.getValor());
                saida[3] = d1.getData();
                saida[4] = d1.getCartao() + "";
                saida[5] = d1.getFixa();
                saida[6] = d1.getParcelas() + "";
                saida[7] = d1.getConta();

                //incluir nova linha na tabela
                model.addRow(saida);
                }
                
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        
        try {
            TelaMenuDeVisualizacao nova;
            nova = new TelaMenuDeVisualizacao();
            nova.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaDescricaoDespesa().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaDescricaoDespesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoListar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxD;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDespesa;
    // End of variables declaration//GEN-END:variables
}
