/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import javax.swing.JOptionPane;
import modelos.entidades.Banco;
import Controle.BancoControle;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.BancoPersistencia;

/**
 *
 * @author ejmcc
 */
public class TelaBanco extends javax.swing.JFrame {

    BancoControle objBancoControle = new BancoControle();
    BancoPersistencia bPersistencia = new BancoPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Bancos.txt");

    /**
     * Creates new form TelaTeste
     */
    public TelaBanco() {
        initComponents();        
        mostrarListagem();
        jTableBancos.setAutoCreateRowSorter(true);
    }

    public void limparTela() {
        jTextFieldIdentificador.setText("");
        jTextFieldDescricao.setText("");
    }

    private void mostrarListagem() {
        try {
            ArrayList<Banco> array = objBancoControle.listagem();
            DefaultTableModel model = (DefaultTableModel) jTableBancos.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < array.size(); pos++) {
                String[] saida = new String[2];
                Banco aux = array.get(pos);
                saida[0] = aux.getId() + "";
                saida[1] = aux.getDescricao();
                //incluir nova linha na tabela
                model.addRow(saida);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIncluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBancos = new javax.swing.JTable();
        jButtonConsultarPorId = new javax.swing.JButton();
        jButtonExcluirPorId = new javax.swing.JButton();
        botaoAlterarBanco = new javax.swing.JButton();
        botaoAlteraId = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");

        jButtonIncluir.setBackground(new java.awt.Color(0, 255, 255));
        jButtonIncluir.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE BANCOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("IDENTIFICADOR");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("DESCRIÇÃO");

        jTextFieldIdentificador.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextFieldIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdentificadorKeyTyped(evt);
            }
        });

        jTextFieldDescricao.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jTableBancos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableBancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "NOME DO BANCO"
            }
        ));
        jScrollPane1.setViewportView(jTableBancos);

        jButtonConsultarPorId.setBackground(new java.awt.Color(0, 255, 255));
        jButtonConsultarPorId.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonConsultarPorId.setText("Consulta por ID");
        jButtonConsultarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPorIdActionPerformed(evt);
            }
        });

        jButtonExcluirPorId.setBackground(new java.awt.Color(0, 255, 255));
        jButtonExcluirPorId.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jButtonExcluirPorId.setText("Excluir por ID");
        jButtonExcluirPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirPorIdActionPerformed(evt);
            }
        });

        botaoAlterarBanco.setBackground(new java.awt.Color(0, 255, 255));
        botaoAlterarBanco.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoAlterarBanco.setText("Alterar descrição");
        botaoAlterarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarBancoActionPerformed(evt);
            }
        });

        botaoAlteraId.setBackground(new java.awt.Color(0, 255, 255));
        botaoAlteraId.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoAlteraId.setText("Alterar id");
        botaoAlteraId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlteraIdActionPerformed(evt);
            }
        });

        botaoVoltar.setBackground(new java.awt.Color(0, 255, 255));
        botaoVoltar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        botaoVoltar.setText("Voltar ao menu principal");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarPorId)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonExcluirPorId)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAlterarBanco)
                        .addGap(22, 22, 22)
                        .addComponent(botaoAlteraId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlteraId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldIdentificador.getText().equals("") || jTextFieldDescricao.getText().equals("")) {
                throw new Exception("Algum dos campos está vazio");
            }
            int id = Integer.parseInt(jTextFieldIdentificador.getText());
            String nomeDoBanco = jTextFieldDescricao.getText();
            Banco objBanco = new Banco(id, nomeDoBanco);

            objBancoControle.incluir(objBanco);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonConsultarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPorIdActionPerformed
        // TODO add your handling code here:
        try {
            String str = jTextFieldIdentificador.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela esta vazio");
            }
            int id = Integer.parseInt(str);
            Banco objBanco = objBancoControle.consultarPorId(id);
            if (objBanco == null) {
                throw new Exception("Banco não existe");
            }
            jTextFieldIdentificador.setText(objBanco.getId() + "");
            jTextFieldDescricao.setText(objBanco.getDescricao());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarPorIdActionPerformed

    private void jButtonExcluirPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirPorIdActionPerformed
        // TODO add your handling code here:
        try {
            String str = jTextFieldIdentificador.getText();
            if (str.length() == 0) {
                throw new Exception("Identificador da tela esta vazio");
            }
            int id = Integer.parseInt(str);
            objBancoControle.apagarPorId(id);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirPorIdActionPerformed

    private void botaoAlterarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarBancoActionPerformed
        try {
            String str1 = jTextFieldIdentificador.getText();
            String str2 = jTextFieldDescricao.getText();
            if (str1.length() == 0||str2.length() == 0) {
                throw new Exception("Algum dos campos não está preenchido");
            }
            
            int id = Integer.parseInt(str1);            
            Banco aux = new Banco();
            aux.setId(id);
            aux.setDescricao(str2);
            objBancoControle.alterarPorId(id, aux);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }//GEN-LAST:event_botaoAlterarBancoActionPerformed

    private void botaoAlteraIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlteraIdActionPerformed
         try {
            String str1 = jTextFieldIdentificador.getText();
            String str2 = jTextFieldDescricao.getText();
            if (str1.length() == 0||str2.length() == 0) {
                throw new Exception("Algum dos campos não está preenchido");
            }
            
            int id = Integer.parseInt(str1);            
            Banco aux = new Banco();
            aux.setId(Integer.parseInt(str1));
            aux.setDescricao(str2);
            objBancoControle.alterarPorDescricao(aux);
            limparTela();
            mostrarListagem();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoAlteraIdActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaMenu nova2 = new TelaMenu();
        this.dispose();
        nova2.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void jTextFieldIdentificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdentificadorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlteraId;
    private javax.swing.JButton botaoAlterarBanco;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton jButtonConsultarPorId;
    private javax.swing.JButton jButtonExcluirPorId;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBancos;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdentificador;
    // End of variables declaration//GEN-END:variables
}
