/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Despesas;
import modelos.entidades.Receitas;
import persistencia.ListagensDeVisualizacao;

/**
 *
 * @author Sciencegamer
 */
public class TelaVisualizarTodos extends javax.swing.JFrame {

    ListagensDeVisualizacao lista = new ListagensDeVisualizacao();

    /**
     * Creates new form TelaVisualizarTodos
     */
    public TelaVisualizarTodos() {
        initComponents();
        mostrarListagem();
        tableLancamentos.setAutoCreateRowSorter(true);
        
    }

    private void mostrarListagem() {
        try {
            ArrayList<Despesas> aux1 = lista.listagemDespesas();
            DefaultTableModel model = (DefaultTableModel) tableLancamentos.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < aux1.size(); pos++) {
                String[] saida = new String[6];
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                Despesas d1 = aux1.get(pos);

                saida[0] = d1.getData();
                saida[1] = df.format(d1.getValor());
                saida[2] = d1.getDescricao();
                saida[3] = d1.getConta() + "";
                saida[4] = d1.getCartao() + "";
                saida[5] = d1.getId() + "";

                //incluir nova linha na tabela
                model.addRow(saida);
            }

            ArrayList<Receitas> aux2 = lista.listagemReceitas();

            for (int pos = 0; pos < aux2.size(); pos++) {
                String[] saida = new String[6];
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                Receitas r1 = aux2.get(pos);

                saida[0] = r1.getData();
                saida[1] = df.format(r1.getValor());
                saida[2] = r1.getDescricao();
                saida[3] = r1.getConta() + "";
                saida[4] = r1.getCartao() + "";
                saida[5] = r1.getId() + "";

                model.addRow(saida);

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLancamentos = new javax.swing.JTable();
        botaoMenuPrincipal = new javax.swing.JButton();
        botaoMenuVis = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TelaVisualizarTodos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "VALOR", "DESCRIÇÃO", "CONTA", "CARTÃO", "IDENTIFICADOR"
            }
        ));
        jScrollPane1.setViewportView(tableLancamentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 750, 200));

        botaoMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoMenuPrincipal.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenuPrincipal.setText("Voltar ao menu principal");
        botaoMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 320, 30));

        botaoMenuVis.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoMenuVis.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoMenuVis.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenuVis.setText("Voltar ao menu de visualização");
        botaoMenuVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuVisActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenuVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("MyCash Financeiro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        TelaVisualizarTodos.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        TelaVisualizarTodos.setForeground(new java.awt.Color(255, 255, 255));
        TelaVisualizarTodos.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaVisualizarTodos.jpg")); // NOI18N
        jPanel1.add(TelaVisualizarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuVisActionPerformed
        TelaMenuDeVisualizacao nova;
        try {
            nova = new TelaMenuDeVisualizacao();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaVisualizarTodos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botaoMenuVisActionPerformed

    private void botaoMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuPrincipalActionPerformed
        TelaMenu nova2 = new TelaMenu();
        this.dispose();
        nova2.setVisible(true);
    }//GEN-LAST:event_botaoMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizarTodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaVisualizarTodos;
    private javax.swing.JButton botaoMenuPrincipal;
    private javax.swing.JButton botaoMenuVis;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLancamentos;
    // End of variables declaration//GEN-END:variables
}
