/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import Controle.UsuarioControle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.entidades.Usuario;
import persistencia.UsuarioPersistencia;


/**
 *
 * @author Sciencegamer
 */
public class TelaRedefinirSenhaUsuario extends javax.swing.JFrame {

    UsuarioControle controle = new UsuarioControle();
    UsuarioPersistencia persistencia = new UsuarioPersistencia("C:\\Users\\Sciencegamer\\ArquivosDadosPI\\Usuarios.txt");

    /**
     * Creates new form TelaRedefinirSenhaUsuario
     */
    public TelaRedefinirSenhaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoVoltarLogin = new javax.swing.JButton();
        botaoConfirmaNovaSenha = new javax.swing.JButton();
        textField3 = new javax.swing.JTextField();
        passField1 = new javax.swing.JPasswordField();
        passField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCash");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel1.setText("Confirmar senha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setText("Nova senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 158, -1));

        botaoVoltarLogin.setBackground(new java.awt.Color(0, 0, 0));
        botaoVoltarLogin.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoVoltarLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltarLogin.setText("Tela login");
        botaoVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarLoginActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 160, -1));

        botaoConfirmaNovaSenha.setBackground(new java.awt.Color(0, 0, 0));
        botaoConfirmaNovaSenha.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoConfirmaNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        botaoConfirmaNovaSenha.setText("Redefinir");
        botaoConfirmaNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaNovaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoConfirmaNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 160, -1));
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, -1));
        jPanel1.add(passField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 150, -1));
        jPanel1.add(passField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 150, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel4.setText("Usuário:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 154, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel8.setText("MyCash Financeiro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel16.setText("A senha deve conter");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 20));

        jLabel21.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel21.setText("(1) Uma letra");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 120, 20));

        jLabel19.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel19.setText("(2) Um número");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 20));

        jLabel20.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel20.setText("(2) Um caracter especial");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 210, 20));

        jLabel15.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel15.setText("(3) 8 caracteres");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 180, 20));

        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaRedefinirSenha.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarLoginActionPerformed
        
        TelaLogin login;
        try {
            this.dispose();
            login = new TelaLogin();
            login.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaRedefinirSenhaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoVoltarLoginActionPerformed

    private void botaoConfirmaNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaNovaSenhaActionPerformed

        try {
            controle.alterarSenha(passField1.getText(), passField2.getText(), textField3.getText());
            JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso!");
            Usuario novo = new Usuario(textField3.getText(), passField1.getText());
            persistencia.alterarSenha(novo, textField3.getText());
            this.dispose();
            TelaLogin login = new TelaLogin();
            this.dispose();
            login.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }

    }//GEN-LAST:event_botaoConfirmaNovaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirSenhaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirSenhaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirSenhaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRedefinirSenhaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRedefinirSenhaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoConfirmaNovaSenha;
    private javax.swing.JButton botaoVoltarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passField1;
    private javax.swing.JPasswordField passField2;
    private javax.swing.JTextField textField3;
    // End of variables declaration//GEN-END:variables
}
