/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.entidades.Despesas;
import modelos.entidades.Receitas;
import persistencia.ListagensDeVisualizacao;

/**
 *
 * @author Sciencegamer
 */
public class TelaLancamentosDoMes extends javax.swing.JFrame {

    ListagensDeVisualizacao lista = new ListagensDeVisualizacao();

    /**
     * Creates new form TelaLancamentosDoMes
     */
    public TelaLancamentosDoMes() {
        initComponents();
        tableLancamentos.setAutoCreateRowSorter(true);
        comboBoxAno.removeAllItems();
        comboBoxAno.addItem("2020");
        comboBoxAno.addItem("2021");
        comboBoxAno.addItem("2022");
        comboBoxAno.addItem("2023");
        comboBoxAno.addItem("2024");
        comboBoxAno.addItem("2025");
        comboBoxMes.removeAllItems();
        comboBoxMes.addItem("Janeiro");
        comboBoxMes.addItem("Fevereiro");
        comboBoxMes.addItem("Março");
        comboBoxMes.addItem("Abril");
        comboBoxMes.addItem("Maio");
        comboBoxMes.addItem("Junho");
        comboBoxMes.addItem("Julho");
        comboBoxMes.addItem("Agosto");
        comboBoxMes.addItem("Setembro");
        comboBoxMes.addItem("Outubro");
        comboBoxMes.addItem("Novembro");
        comboBoxMes.addItem("Dezembro");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLancamentos = new javax.swing.JTable();
        botaoMenuPrincipal = new javax.swing.JButton();
        botaoMenuVis = new javax.swing.JButton();
        comboBoxAno = new javax.swing.JComboBox<>();
        botaoLancamentos = new javax.swing.JButton();
        comboBoxMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "VALOR", "DESCRIÇÃO", "CONTA", "CARTÃO", "IDENTIFICADOR"
            }
        ));
        jScrollPane1.setViewportView(tableLancamentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 930, 270));

        botaoMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoMenuPrincipal.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenuPrincipal.setText("Menu principal");
        botaoMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, 30));

        botaoMenuVis.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoMenuVis.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoMenuVis.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenuVis.setText("Menu de visualização");
        botaoMenuVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuVisActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenuVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 260, 30));

        comboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAnoActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 86, 30));

        botaoLancamentos.setBackground(new java.awt.Color(0, 0, 0,60));
        botaoLancamentos.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        botaoLancamentos.setForeground(new java.awt.Color(255, 255, 255));
        botaoLancamentos.setText("Lançamentos do mês");
        botaoLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLancamentosActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLancamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 86, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ano:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 50, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mês:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 71, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel9.setText("MyCash Lançamentos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        TelaFundo.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        TelaFundo.setForeground(new java.awt.Color(255, 255, 255));
        TelaFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dener\\Documents\\NetBeansProjects\\ProjetoControleFinanceiro-2.0.3\\TelasPlanosDeFundo\\TelaLançamentosMês.jpg")); // NOI18N
        jPanel1.add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1030, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuPrincipalActionPerformed
        TelaMenu nova2 = new TelaMenu();
        this.dispose();
        nova2.setVisible(true);
    }//GEN-LAST:event_botaoMenuPrincipalActionPerformed

    private void botaoMenuVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuVisActionPerformed

        try {
            TelaMenuDeVisualizacao nova;
            nova = new TelaMenuDeVisualizacao();
            this.dispose();
            nova.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaVisualizarTodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoMenuVisActionPerformed

    private void botaoLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLancamentosActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/yy");
        try {
            ArrayList<Despesas> aux1 = lista.listagemDespesas();
            DefaultTableModel model = (DefaultTableModel) tableLancamentos.getModel();
            model.setNumRows(0);

            String comparador2Ano = comboBoxAno.getSelectedItem() + "";
            comparador2Ano = comparador2Ano.substring(2, 4);
            String comparador2Mes = comboBoxMes.getSelectedItem() + "";

            if (comparador2Mes.equals("Janeiro")) {
                comparador2Mes = "01";
            } else if (comparador2Mes.equals("Fevereiro")) {
                comparador2Mes = "02";
            } else if (comparador2Mes.equals("Março")) {
                comparador2Mes = "03";
            } else if (comparador2Mes.equals("Abril")) {
                comparador2Mes = "04";
            } else if (comparador2Mes.equals("Maio")) {
                comparador2Mes = "05";
            } else if (comparador2Mes.equals("Junho")) {
                comparador2Mes = "06";
            } else if (comparador2Mes.equals("Julho")) {
                comparador2Mes = "07";
            } else if (comparador2Mes.equals("Agosto")) {
                comparador2Mes = "08";
            } else if (comparador2Mes.equals("Setembro")) {
                comparador2Mes = "09";
            } else if (comparador2Mes.equals("Outubro")) {
                comparador2Mes = "10";
            } else if (comparador2Mes.equals("Novembro")) {
                comparador2Mes = "11";
            } else if (comparador2Mes.equals("Dezembro")) {
                comparador2Mes = "12";
            }
            String comparador2 = comparador2Mes + "/" + comparador2Ano;

            for (int pos = 0; pos < aux1.size(); pos++) {
                String[] saida = new String[6];

                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                Despesas d1 = aux1.get(pos);

                String comparador1 = d1.getData();
                comparador1 = comparador1.substring(3, 8);
                
                if(d1.getFixa().equals("Despesa fixa")){
                    saida[0] = d1.getData();
                    saida[1] = df.format(d1.getValor());
                    saida[2] = d1.getDescricao();
                    saida[3] = d1.getConta() + "";
                    saida[4] = d1.getCartao() + "";
                    saida[5] = d1.getId() + "";
                    model.addRow(saida);
                }
                else if (comparador1.equals(comparador2)) {
                    saida[0] = d1.getData();
                    saida[1] = df.format(d1.getValor());
                    saida[2] = d1.getDescricao();
                    saida[3] = d1.getConta() + "";
                    saida[4] = d1.getCartao() + "";
                    saida[5] = d1.getId() + "";
                    model.addRow(saida);
                }

            }

            ArrayList<Receitas> aux2 = lista.listagemReceitas();

            for (int pos = 0; pos < aux2.size(); pos++) {
                String[] saida = new String[6];
                DecimalFormat df = new DecimalFormat("R$#,##0.00");
                Receitas r1 = aux2.get(pos);

                String comparador1 = r1.getData();
                comparador1 = comparador1.substring(3, 8);

                if (comparador1.equals(comparador2)) {
                    saida[0] = r1.getData();
                    saida[1] = df.format(r1.getValor());
                    saida[2] = r1.getDescricao();
                    saida[3] = r1.getConta() + "";
                    saida[4] = r1.getCartao() + "";
                    saida[5] = r1.getId() + "";
                    model.addRow(saida);
                }

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_botaoLancamentosActionPerformed

    private void comboBoxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentosDoMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentosDoMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentosDoMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentosDoMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLancamentosDoMes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton botaoLancamentos;
    private javax.swing.JButton botaoMenuPrincipal;
    private javax.swing.JButton botaoMenuVis;
    private javax.swing.JComboBox<String> comboBoxAno;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLancamentos;
    // End of variables declaration//GEN-END:variables
}
